Skip over valueless words in find_metrical_position.
Some words have no metrical value of their own--they scan as ''. Skip
ahead to the next word with syllables.

This was the cause of an exception:
      File "metricalposition", line 226, in find_metrical_position
        if words[offset][0] == "+":
    IndexError: string index out of range